### ISSUE TITLE
How to change input size

### ISSUE THREAD

**Issue by vincent9619** [argusswift/YOLOv4-pytorch#1]
Hi,  I used my dataset to train the model, it came out an error: ValueError: Target size (torch.Size([1, 52, 52, 3, 1])) must be the same as input size (torch.Size([1, 52, 52, 3, 20])).
  How should I change the input size or target size to make input and the target have the same size? Thank you!

**Comment by argusswift** [comment]
Are you using PASCAL VOC dataset to train your model?
It seem that your have modified the input number of category.
It will be nice of you to tell more details so that we could deal with this issue

**Comment by vincent9619** [comment]
yeah, Im using voc dataset and just train single class. I have already changed the class name and number in the config file.

**Comment by argusswift** [comment]
Hi, this issue is emerged from line 29 in model/build_model.py.
The original code:`self.__nC = 20 if cfg.TRAIN["DATA_TYPE"] == 'VOC' else 80`
should be: `self.__nC = cfg.VOC_DATA["NUM"] if cfg.TRAIN["DATA_TYPE"] == 'VOC' else cfg.COCO_DATA["NUM"]
`
Thus, it seem that I should update some code to avoid something like this.

**Comment by vincent9619** [comment]
It works now, thank you so much! I'll close this issue.
